name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:assignment5
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Run full test
            run: ./full-test.sh
